
package com.itcast.redsun.bos.ws.impl;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.itcast.redsun.bos.ws.ObjectFactory;
import com.itcast.redsun.bos.ws.Waybilldetail;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IWaybillWs", targetNamespace = "http://ws.bos.redsun.itcast.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IWaybillWs {


    /**
     * 
     * @param tele
     * @param addressee
     * @param arg4
     * @param toaddress
     * @param userId
     * @return
     *     returns java.lang.Long
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addWaybill", targetNamespace = "http://ws.bos.redsun.itcast.com/", className = "com.itcast.redsun.bos.ws.AddWaybill")
    @ResponseWrapper(localName = "addWaybillResponse", targetNamespace = "http://ws.bos.redsun.itcast.com/", className = "com.itcast.redsun.bos.ws.AddWaybillResponse")
    public Long addWaybill(
        @WebParam(name = "arg0", targetNamespace = "")
        Long userId,
        @WebParam(name = "arg1", targetNamespace = "")
        String toaddress,
        @WebParam(name = "arg2", targetNamespace = "")
        String addressee,
        @WebParam(name = "arg3", targetNamespace = "")
        String tele,
        @WebParam(name = "arg4", targetNamespace = "")
        String info);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.itcast.redsun.bos.ws.Waybilldetail>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "waybilldetailList", targetNamespace = "http://ws.bos.redsun.itcast.com/", className = "com.itcast.redsun.bos.ws.WaybilldetailList")
    @ResponseWrapper(localName = "waybilldetailListResponse", targetNamespace = "http://ws.bos.redsun.itcast.com/", className = "com.itcast.redsun.bos.ws.WaybilldetailListResponse")
    public List<Waybilldetail> waybilldetailList(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

}
